apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx  # Match the labels to select the Pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP