apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx  # Add labels to the Pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80